### PR TITLE
Barebones GitHub Actions CI pipeline

### LINKED ISSUE #3: Tests
Not sure exactly how we test plotting through CI, but we should have some kind of tests

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Might take a bit of work but CI ~should at least be quick!~ actually no, GLMakie.jl is a pretty heavy dependency...

Resolves #3

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
CI still complains about not being able to build GLFW.jl but I'll ask on Julia Slack, maybe I missed a step.

**Comment by sandreza** [comment]
Thanks for taking this on Ali!

**Comment by jakebolewski** [comment]
Is it this issue?  https://github.com/JuliaGL/GLFW.jl/issues/198

**Comment by ali-ramadhan** [comment]
@jakebolewski Potentially! Linking to the system libstdc++ has worked for me on another headless system in the past.

I noticed that GLMakie.jl installed some packages via `apt-get` and sets some environment variables in their `ci.yml`

https://github.com/JuliaPlots/GLMakie.jl/blob/master/.github/workflows/ci.yml

which seems to work as their tests pass, e.g.

https://github.com/JuliaPlots/GLMakie.jl/runs/1887506352?check_suite_focus=true

so I'm thinking we should also be able to get GLMakie.jl to work on GHA if we use a very similar `ci.yml`. But maybe it requires more than just copy pasting...

**Comment by ali-ramadhan** [comment]
GLMakie.jl builds and tests pass on GHA! Thank you @Libbum for the Ubuntu tip!

**Pull request merged**
